fix #10: allow unpinned local actions
zgosalvez/github-actions-ensure-sha-pinned-actions pull request #11
Opened 2021-11-02 08:57 UTC by xunleii

2021-11-02 10:23 UTC, zgosalvez requested changes

2021-11-02 10:23 UTC, zgosalvez commented on src/index.js
> +          if (uses.includes('@') && !assertUsesSHA(uses)) {
```suggestion
          if (!assertUsesSHA(uses)) {
```

2021-11-02 10:23 UTC, zgosalvez commented on src/index.js
> +            if (typeof uses === 'string' && uses.includes('@') && !assertUsesSHA(uses)) {
```suggestion
            if (!assertUsesSHA(uses)) {
```

2021-11-02 12:16 UTC, xunleii commented on src/index.js
> +          if (uses.includes('@') && !assertUsesSHA(uses)) {
@zgosalvez On the `v1.0.4` release, this Github Action only ensure that GitHub Actions are pinned to full length commit SHAs. 
When I wrote my PR (#7), I forgot to only check a Github Action if it contains a `@`, forcing this validation for [local action](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow) or a [Docker action](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-a-docker-hub-action). So, checking if a `@` exists before checking if the reference is a SHA will fix the regression.

2021-11-03 02:20 UTC, zgosalvez commented
I'll revisit this weekend, and I'll see if I can have some tests included to catch these use cases. Thank you for your patience.

2021-11-07 02:09 UTC, zgosalvez commented
@xunleii, please check #12 and consider closing this PR.

2021-11-11 17:13 UTC, closed without merging